### ISSUE TITLE
Create a way to generate predictable and automatic ids

### ISSUE THREAD

**Issue by JoaoTMDias** [feedzai/react-a11y-tools#5]
**Is your feature request related to a problem? Please describe.**
Accessibility APIs rely heavily on element IDs and requiring developers to put IDs on every element on a component library is both cumbersome and error-prone. With a component model, there should be a way to generate IDs for them!

**Describe the solution you'd like**
Incrementing an id seems like a pretty reasonable solution, with safeguards for server-side rendering apps.
Since we're rendering the exact same tree on the server and client, we can increment a counter and get a deterministic result between client and server.
Plus, adding a prefixed id can help to generate unique and predictable id's.

**Additional context**
This should be available to be imported as a custom hook called `useId` or `useAutoId`.

**Comment by waldyrious** [comment]
@JoaoTMDias just out of curiosity, can you clarify why this issue was closed?

**Comment by waldyrious** [comment]
Oh, I see, it was fixed in #6. Nevermind :)
